DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
    BRAND_ID   SMALLINT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRICE_LIST INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE   TIMESTAMP NOT NULL,
    PRIORITY SMALLINT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR CHAR(3) NOT NULL,
    CONSTRAINT PK_Prices PRIMARY KEY (BRAND_ID,PRODUCT_ID, PRICE_LIST)
);